
# Site settings
title: Josan and Bryan Wedding

description: > # this means to ignore newlines until "baseurl:"
  Once in a while, right in the middle of an ordinary life, love gives us a fairytale.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

ceremony:
  groom:
    name: Bryan Carl Chug
    description: "He is a great programmer who solves any problem through logic and reason. He also loves beer and a movie junkie as well. The founder of a Aestrea Software Development company, a startup and consulting company exclusively working for rocketmiles.com (a Priceline company)."

  bride:
    name: Josan Astrid Dometita
    description: "She is a codesigner (coder-designer), the Google Developer Group and Women Techmakers Community Lead for Cagayan de Oro. Josan's personal advocacy is inspiring women to become a techmaker. Currently, she plays around with her Gemma KIT, a Do-It-Yourslef wearable kit and travels to different places to share great things about it. She's also a UI/UX Engineer and co-founder of Aestrea Software Development."


people:
  bestman:
    name: Gerardo Guangco
    image: 'gerardo.png'

  maidofhonor:
    name: Rochelle Barros
    image: 'rochelle.png'

  groomsmen:
    - name: Elmer Labella
      image: 'elmer.png'
      

    - name: Dino Antonio Poblete
      image: 'dino.png'
      

    - name: Joey Sendaydiego
      image: 'senday.png'
      

    - name: Edrick Lim
      image: 'edrick.png'
      

    - name: Josh Gatchalian
      image: 'josh.png'
      

    - name: Kim Carl Filomeno
      image: 'kim.png'
      

  bridesmaid:
    - name: Jenny Ferrer
      image: 'jenny.png'
      

    - name: Rizza Marie Dometita
      image: 'rizza.png'
      

    - name: Jizea Mee Baltazar
      image: 'jizea.png'
      

    - name:  Michelle Mae Ong
      image: 'michelle.png'
      

    - name: April Anne Belandres
      image: 'april.png'
      

    - name: Janine April Tolentino
      image: 'janine.png'

supplier:
  - name:  "Palazzo Verde"
    product: "Venue"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/15.png"

  - name: "Threelogy Video"
    product: "Videography"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/1.png"

  - name:  "Hugbig"
    product: "Photography"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/10.png"

  - name: "Vatel Manila"
    product: "Entourage Flowers & Bridal Bouquet"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/2.png"

  - name:  "Aljoe Mix"
    product: "Lights, Sounds, and LED Wall"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/3.png"

  - name:  "Josiah's Catering"
    product: "Caterer"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/4.png"

  - name:  "4th Wall Production Design Station"
    product: "Event Styling"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/5.png"

  - name:  "Manila Philharmonic Orchestra"
    product: "Musician"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/6.png"

  - name:  "Piece of Cake by Yumi Castrillo"
    product: "Cake"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/7.png"

  - name:  "Flip Productions"
    product: "Photo booth"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/8.png"

  - name:  "Avi Capili-Bobadilla"
    product: "Bridal Gown"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/9.png"

  - name:  "Graciela Claudio"
    product: "Bridal Makeup"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/11.png"

  - name:  "Living Gifts"
    product: "Souvenirs"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/12.png"

  - name:  "Kist and Makeup"
    product: "HMUA"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/13.png"

  - name:  "Shayne Ganalon Weddings & Events Management"
    product: "OTD Coordination"
    image: "https://res.cloudinary.com/design-studio/image/upload/jandbwedding/14.png"








