
# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

ceremony:
  groom:
    name: Bryan Carl Chug
    description: "He is a great programmer who solves any problem through logic and reason. He also loves beer and a movie junkie as well. The founder of a Aestrea Software Development company, a startup and consulting company exclusively working for rocketmiles.com (a Priceline company)."

  bride:
    name: Josan Astrid Dometita
    description: "She is a codesigner (coder-designer), the Google Developer Group and Women Techmakers Community Lead for Cagayan de Oro. Josan's personal advocacy is inspiring women to become a techmaker. Currently, she plays around with her Gemma KIT, a Do-It-Yourslef wearable kit and travels to different places to share great things about it. She's also a UI/UX Engineer and co-founder of Aestrea Software Development."


people:
  bestman:
    name: Gerardo Guangco
    image: 'groomsmen.jpg'

  maidofhonor:
    name: Rochelle Barros
    image: 'bridesmaid.jpg'

  groomsmen:
    - name: Elmer Labella
      image: 'groomsmen.jpg'
      relation: Friend

    - name: Dino Antonio Poblete
      image: 'groomsmen.jpg'
      relation: Friend

    - name: Joey Sendaydiego
      image: 'groomsmen.jpg'
      relation: Friend

    - name: Edrick Lim
      image: 'groomsmen.jpg'
      relation: Friend

    - name: Josh Gatchalian
      image: 'groomsmen.jpg'
      relation: Friend

    - name: Kim Carl Filomeno
      image: 'groomsmen.jpg'
      relation: Friend

  bridesmaid:
    - name: Jenny Ferrer
      image: 'bridesmaid.jpg'
      relation: Friend

    - name: Rizza Marie Dometita
      image: 'bridesmaid.jpg'
      relation: Friend

    - name: Jizea Mee Baltazar
      image: 'bridesmaid.jpg'
      relation: Friend

    - name: Michelle Mae Ong
      image: 'bridesmaid.jpg'
      relation: Friend

    - name: April Anne Belandres
      image: 'bridesmaid.jpg'
      relation: Friend

    - name: Janine April Tolentino
      image: 'bridesmaid.jpg'
      relation: Friend









